version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.txt
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
